import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = path.join(rootDir, "src", "plugin-sdk-compat");
const outDir = path.join(rootDir, "dist", "plugin-sdk-compat");

const compatEntries = [
  "agent-runtime",
  "allow-from",
  "channel-config-schema",
  "channel-feedback",
  "channel-runtime",
  "channel-status",
  "command-auth",
  "config-runtime",
  "index",
  "infra-runtime",
  "param-readers",
  "reply-history",
  "reply-runtime",
  "routing",
  "setup",
  "temp-path",
  "text-runtime",
  "tool-send",
  "zalouser",
] as const;

const generatedHeader = "// Generated by scripts/write-plugin-sdk-compat.ts\n";

const compatDtsByEntry: Record<(typeof compatEntries)[number], string> = {
  "agent-runtime": 'export * from "../plugin-sdk/index.js";\n',
  "allow-from": 'export * from "../plugin-sdk/index.js";\n',
  "channel-config-schema": 'export { buildChannelConfigSchema } from "../plugin-sdk/index.js";\n',
  "channel-feedback": 'export * from "../plugin-sdk/index.js";\n',
  "channel-runtime": 'export { createTypingCallbacks } from "../plugin-sdk/index.js";\n',
  "channel-status": `export {
  PAIRING_APPROVED_MESSAGE,
  buildBaseAccountStatusSnapshot,
  buildBaseChannelStatusSummary,
  buildTokenChannelStatusSummary,
  collectStatusIssuesFromLastError,
  createDefaultChannelRuntimeState,
} from "../plugin-sdk/index.js";
`,
  "command-auth": `export { resolveSenderCommandAuthorizationWithRuntime } from "../plugin-sdk/index.js";
export declare function resolveDirectDmAuthorizationOutcome(params?: {
  isGroup?: boolean;
  dmPolicy?: string;
  senderAllowedForCommands?: boolean;
}): "allowed" | "disabled" | "unauthorized";
`,
  "config-runtime": `export declare function loadConfig(): Record<string, unknown>;
export declare function writeConfigFile(
  cfg: unknown,
  options?: { expectedConfigPath?: string },
): Promise<void>;
`,
  index: 'export * from "../plugin-sdk/index.js";\n',
  "infra-runtime": 'export { resolvePreferredOpenClawTmpDir, withFileLock } from "../plugin-sdk/index.js";\n',
  "param-readers": 'export * from "../plugin-sdk/index.js";\n',
  "reply-history": 'export * from "../plugin-sdk/index.js";\n',
  "reply-runtime": 'export * from "../plugin-sdk/index.js";\n',
  routing: 'export * from "../plugin-sdk/index.js";\n',
  setup: 'export * from "../plugin-sdk/index.js";\n',
  "temp-path": 'export * from "../plugin-sdk/index.js";\n',
  "text-runtime": 'export { stripMarkdown } from "../plugin-sdk/index.js";\n',
  "tool-send": 'export * from "../plugin-sdk/index.js";\n',
  zalouser: 'export * from "../plugin-sdk/index.js";\n',
};

const rewriteRuntimeSource = (source: string) =>
  source.replaceAll("../../dist/plugin-sdk/index.js", "../plugin-sdk/index.js");

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

for (const entry of compatEntries) {
  const srcPath = path.join(srcDir, `${entry}.js`);
  const outJsPath = path.join(outDir, `${entry}.js`);
  const outDtsPath = path.join(outDir, `${entry}.d.ts`);

  const runtimeSource = fs.readFileSync(srcPath, "utf8");
  fs.writeFileSync(outJsPath, generatedHeader + rewriteRuntimeSource(runtimeSource), "utf8");
  fs.writeFileSync(outDtsPath, generatedHeader + compatDtsByEntry[entry], "utf8");
}
